# Generated by Django 6.0.4 on 2026-05-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_avatar_userprofile_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pro_approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pro_coupon_used",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pro_request_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="pro_requested",
            field=models.BooleanField(default=False),
        ),
    ]
