# Generated by Django 6.0.4 on 2026-04-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagram_preference", models.FloatField(default=0.0)),
                ("analogy_preference", models.FloatField(default=0.0)),
                ("example_preference", models.FloatField(default=0.0)),
                ("theory_preference", models.FloatField(default=0.0)),
                ("logic_preference", models.FloatField(default=0.0)),
                ("interaction_count", models.PositiveIntegerField(default=0)),
                (
                    "preferred_style",
                    models.CharField(
                        choices=[
                            ("diagram", "Diagram"),
                            ("analogy", "Analogy"),
                            ("example", "Example"),
                            ("theory", "Theory"),
                            ("logic", "Logic"),
                            ("balanced", "Balanced"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        blank=True, help_text="Optional 1-5 rating from user", null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "content_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="learning.contentversion",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_interactions",
                        to="learning.topic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("user", "content_version")},
            },
        ),
    ]
