# Generated by Django 6.0.4 on 2026-04-07 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="bi-book",
                        help_text="Bootstrap icon class",
                        max_length=100,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6c5ce7", help_text="Hex color for card", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField(blank=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in subject"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="learning.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title"],
                "unique_together": {("subject", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "style_type",
                    models.CharField(
                        choices=[
                            ("diagram", "Diagram-Focused"),
                            ("analogy", "Analogy-Focused"),
                            ("example", "Example-Focused"),
                            ("theory", "Theory-Focused"),
                            ("logic", "Logic-Focused"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The actual explanation content for this style"
                    ),
                ),
                (
                    "diagram_score",
                    models.IntegerField(
                        default=0, help_text="0-100: How diagram-heavy is this content"
                    ),
                ),
                (
                    "analogy_score",
                    models.IntegerField(
                        default=0, help_text="0-100: How analogy-heavy is this content"
                    ),
                ),
                (
                    "example_score",
                    models.IntegerField(
                        default=0, help_text="0-100: How example-heavy is this content"
                    ),
                ),
                (
                    "theory_score",
                    models.IntegerField(
                        default=0, help_text="0-100: How theory-heavy is this content"
                    ),
                ),
                (
                    "logic_score",
                    models.IntegerField(
                        default=0, help_text="0-100: How logic-heavy is this content"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_versions",
                        to="learning.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["style_type"],
            },
        ),
        migrations.CreateModel(
            name="VideoResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("youtube_url", models.URLField(help_text="Full YouTube URL")),
                ("description", models.TextField(blank=True)),
                ("diagram_score", models.IntegerField(default=0)),
                ("analogy_score", models.IntegerField(default=0)),
                ("example_score", models.IntegerField(default=0)),
                ("theory_score", models.IntegerField(default=0)),
                ("logic_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="learning.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
