# Generated by Django 6.0.4 on 2026-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinteraction",
            name="skipped",
            field=models.BooleanField(
                default=False, help_text="True if user clicked Not Interested"
            ),
        ),
    ]
